##teamcity[testSuiteStarted name='tst_Xunit']
##teamcity[testStarted name='initTestCase()']
##teamcity[testFinished name='initTestCase()']
##teamcity[testStarted name='testFunc1()']
##teamcity[testStdOut name='testFunc1()' out='WARNING |[Loc: tst_xunit.cpp(59)|]: just a QWARN() !']
##teamcity[testFinished name='testFunc1()']
##teamcity[testStarted name='testFunc2()']
##teamcity[testFailed name='testFunc2()' message='Failure! |[Loc: tst_xunit.cpp(66)|]' details='Compared values are not the same|n Actual (2): 2|n Expected (3): 3']
##teamcity[testStdOut name='testFunc2()' out='QDEBUG: a qDebug() call with comment-ending stuff -->']
##teamcity[testFinished name='testFunc2()']
##teamcity[testIgnored name='testFunc3()' message='skipping this function! |[Loc: tst_xunit.cpp(71)|]']
##teamcity[testStarted name='testFunc4()']
##teamcity[testFailed name='testFunc4()' message='Failure! |[Loc: tst_xunit.cpp(76)|]' details='a forced failure!']
##teamcity[testFinished name='testFunc4()']
##teamcity[testStarted name='testFunc5()']
##teamcity[testStdOut name='testFunc5()' out='XFAIL |[Loc: tst_xunit.cpp(90)|]: this failure is expected']
##teamcity[testFinished name='testFunc5()']
##teamcity[testStarted name='testFunc6()']
##teamcity[testStdOut name='testFunc6()' out='XFAIL |[Loc: tst_xunit.cpp(96)|]: this failure is also expected']
##teamcity[testFinished name='testFunc6()']
##teamcity[testStarted name='testFunc7()']
##teamcity[testFailed name='testFunc7()' message='Failure! |[Loc: tst_xunit.cpp(102)|]' details='|'true|' returned TRUE unexpectedly. ()']
##teamcity[testFinished name='testFunc7()']
##teamcity[testStarted name='cleanupTestCase()']
##teamcity[testFinished name='cleanupTestCase()']
##teamcity[testSuiteFinished name='tst_Xunit']
